name: CI

on:
  push:
    branches:
      - main
    tags:
      - '*'

permissions:
  contents: write
  issues: write
  pull-requests: write
  actions: write
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Validate package
        uses: heyhusen/archlinux-package-action@v2

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          tag_name="${GITHUB_REF#refs/tags/}"
          echo "Creating release for tag: $tag_name"
          curl -XPOST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d "{\"tag_name\":\"$tag_name\", \"name\":\"Release $tag_name\", \"body\":\"Release notes for $tag_name\"}" \
            "https://api.github.com/repos/${{ github.repository }}/releases"
